### ISSUE TITLE
Sidebar ordering not working

### ISSUE THREAD

**Issue by ygtc** [jneilliii/OctoPrint-DragonOrder#6] opened 2018-11-25 01:52 UTC
I can't order my siderbar :/ tabs are ok and navbar ok. I'm using your other plugins are consolidate temp control and taborder. 

Is might be reason about sidebar can not order?

**Comment by jneilliii** [comment] 2018-11-25 04:30
Which version did you install?  The latest version introduced a filter that allows the dragging only on the header row of the sidebar panels so make sure you're grabbing a white space next to the title of the panel.

**Comment by ygtc** [comment] 2018-11-30 22:17
sorry for late response but;

installed 0.1.2 version and also yes, i try to grab from only header row of sidebar items but not work :/ Did i something wrong ?

**Comment by jneilliii** [comment] 2018-12-01 00:36
What other plugins do you have installed?  I wonder if there may be a conflict with something else.  It's working fine for me.  One thing that may help, is minimizing all the sidebar panels so you aren't having to move them as much to get them where you want them.

**Comment by jneilliii** [comment] 2018-12-13 05:34
Same question, what other plugins do you have installed, specifically in the sidebar. Any errors in the browser's developer console or octoprint.log? What browser?

**Comment by Kab14523** [comment] 2019-01-05 21:39
Same for me, too. I checked with Firefox 64.0 and Chrome 71.0.3578.98. DragonOrder Plugin 0.1.2. Other Plugins are:
- Automatic Shutdown 0.1.4 (I tried disabling it)
- Sidebar Temp Graph (0.1.2) (I disabled this too)
- System Command Editor (0.3.2)
- OctoPrint-IFTTT (1.0.2)
- Navbar Temperature Plugin (0.11)
- Display ETA (1.0.1)
- EEPROM Marlin Editor Plugin (1.2.1)
- FileManager (0.1.3)
- BetterHeaterTimeout (1.1.0)
- the standard ones...

When I minimise the sidebar entries by clicking on the name I get an TypeError in the firefox console:
TypeError: $(...).find(...).andSelf is not a function[Weitere Informationen] packed_plugins.js:5333:58
_mouseCapture
http://192.168.X.XX/static/webassets/packed_plugins.js:5333:58
$.widget/</prototype[prop]</<
(I put the X.XX there)

Same happens wenn I click on the empty space next to it. So I guess this could be the source of the error?
Nothing in the octoprint log.

**Comment by jneilliii** [comment] 2019-01-05 21:59
Strange. Did you disable both plugins at the same time? What is the code when you click on the url in the console like `http://192.168.x.xx/static/webassets/packed_plugins.js:5333:58` above?

**Comment by Kab14523** [comment] 2019-01-05 23:33
Yes I disabled them both at the same time but only checked in Firefox. The code is:
`var validHandle = false;
$(this.options.handle, currentItem).find("*").andSelf().each(function() { if(this == event.target) validHandle = true; });`

**Comment by R0dri** [comment] 2019-02-21 16:04
Having the same trouble, any update?

**Comment by jneilliii** [comment] 2019-02-21 18:49
Maybe this a language issue for some reason, not sure why.  @R0dri, is yours also in German(?)? Maybe I have another plugin installed that is making it work as expected that you guys don't have, although I don't see why that would be the case.  I'm in the process now of setting up my python3 dev environment to test my plugins, so I have a clean OctoPrint install and will test this out there to see.

**Comment by jneilliii** [comment] 2019-02-21 19:50
So just installed in brand new environment and it is still working without issue for me, so at this point not really sure why this is happening.

**Comment by R0dri** [comment] 2019-02-22 03:12
looks weird. No, I am in English. I'll try to disable every plugin/mod to sort out if it is a plugin or maybe a buggy installation that I have. I will also try a brand new environment, test it is working as you said, then proceed to install all my plugins in batches to see what is going on. Let you know in a couple of days what I can find.

**Comment by JdeV987** [comment] 2019-03-02 23:20
I have the same problem, can sort everything except sidebars, running OctoPrint: 1.3.10 .
Have these other plugins installed:
 Action Command Prompt
 Bed Leveling Wizard
 CuraEngine (<= 15.04)
 E-Stop Settings
 EEPROM Marlin Editor Plugin
 Fan Speed Control
 Heater Timeout
 Navbar Temperature Plugin
 System Command Editor
 Yamlpatcher

**Comment by jneilliii** [comment] 2019-03-02 23:41
Have you guys tried minimizing the panels first to make it easier to move? The sidebar panels can only be moved up and down in the sidebar. Are any of your instances publically available and you're willing to share a login with me to see it for myself? I've installed the plugin on 3 different pi installs and 2 windows installed and it's worked on every one of them.

**Comment by JdeV987** [comment] 2019-03-06 11:51
Yes, panels are minimized. Still can't move the menu items. I use Win.7, 64bit, not sure if that is a factor.

**Comment by 3113Project** [comment] 2019-03-22 16:47
I disabled "Action Command Prompt" then it work.

**Comment by jneilliii** [comment] 2019-03-24 19:50
Can you send me the link to that plugin's homepage?

**Comment by ygtc** [comment] 2019-03-24 20:21
Action Command Prompt comes with octoprint which created by Gina Häußge.

I can send you to ss about plugin.

![actioncommand](https://user-images.githubusercontent.com/39675823/54885283-7f058680-4e8b-11e9-89ca-634c1b12698e.jpg)

I hope you figured it out error :sweat_smile: 

:eyes: :eyes:

**Comment by ygtc** [comment] 2019-03-24 20:31
Btw i tried also Action Command Prompt to disable but still not working for me:/

Just in case maybe you found conflict with Action Command Prompt and this issue might be solved.

**Comment by Kab14523** [comment] 2019-03-27 21:01
Hi, I also had no luck with disabling Action Command Prompt.

**Comment by jneilliii** [comment] 2019-03-29 19:58
Been tied up at work.  Are any of you guys using Chrome?  Can you try in a new incognito window to see if is the same thing? Is anyone willing to do a screen sharing session with me so I can look specifically at their implementation and do some debugging since I am still unable to reproduce this issue you are experiencing.

**Comment by Pheelix** [comment] 2019-04-28 15:44
After Disabling/Uninstalling System Command Editor my Sidebar Ordering worked again.  I think this is the plugin causing the problem.  Someone want to try disabling/uninstalling System Command Editor and see if it fixes it for them?

**Comment by ygtc** [comment] 2019-05-08 15:09
I am not using System Command Editor but i tried to disable/uninstall custom control editor. No chance :disappointed: 

Still same.

**Comment by Pheelix** [comment] 2019-05-08 20:03
I recommend disabling each plugin one by one until it does work.  That is what I did.  It is a slow process due to restarts, but it is the only way I can think of to find out what plugin is conflicting.

**Comment by NovaViper** [comment] 2019-06-09 02:27
@jneilliii For me, the Conslidate Temp and Control plugin was what caused the Dragon plugin to stop functioning on the sidebar.

**Comment by JdeV987** [comment] 2019-07-06 07:27
After disabling "System Command Editor", DragonOrder worked again on the sidebar menus..

**Comment by jneilliii** [comment] 2019-07-06 16:38
Ok, I see the reason for this.  It appears that the System Command Editor plugin is also implementing a jquery.ui.sortable library, which is probably conflicting with this plugin's version.  I assume any of the other plugin's that also implement a different version would cause this.  The Consolidate Temp and Control plugin changes the spans classes used by this plugin to identify the sidebar panels.  In either case, the DragonOrder plugin does not need to be loaded for the ordering to work properly once you've re-ordered with the plugin.  So disable the conflicting plugins and enable this one, order the things the way you want them and then disable this plugin and enable the others.

**Comment by Kab14523** [comment] 2019-08-20 20:36
With the new update from SystemCommandEditor by Salandora (version 0.3.3) it now works. Thanks @jneilliii for the great work!

**Comment by jneilliii** [comment] 2019-08-20 21:36
Glad to hear. Thanks to @Salandora for merging my pull request.

**Closed by jneilliii** 2019-08-20 21:36 UTC

**Comment by Salandora** [comment] 2019-08-25 20:22
@jneilliii thanks for the PR and also glad to hear that it solved this issue.
